/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmIdRouteImport } from './routes/film/$id'

const WishlistIndexLazyRouteImport = createFileRoute('/wishlist/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistIndexLazyRoute = WishlistIndexLazyRouteImport.update({
  id: '/wishlist/',
  path: '/wishlist/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/wishlist/index.lazy').then((d) => d.Route),
)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/film/$id': typeof FilmIdRoute
  '/wishlist/': typeof WishlistIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/film/$id': typeof FilmIdRoute
  '/wishlist': typeof WishlistIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/film/$id': typeof FilmIdRoute
  '/wishlist/': typeof WishlistIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/film/$id' | '/wishlist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/film/$id' | '/wishlist'
  id: '__root__' | '/' | '/film/$id' | '/wishlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmIdRoute: typeof FilmIdRoute
  WishlistIndexLazyRoute: typeof WishlistIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/': {
      id: '/wishlist/'
      path: '/wishlist'
      fullPath: '/wishlist/'
      preLoaderRoute: typeof WishlistIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmIdRoute: FilmIdRoute,
  WishlistIndexLazyRoute: WishlistIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
